\context ChordNames
	\chords {
		\set majorSevenSymbol = \markup { "maj7" }
		\set chordChanges = ##t

		% intro
		a1:m f1:maj7
		a1:m f1:maj7
		a1:m g1 g1 g1 a1:m a1:m
		a1:m g1 g1 d1:m f1 e1:7 e1:7		

		% cordero de dios...
		a1:m e1:m
		f1 c1
		d1:m a1:m f1 e1:7 e1:7

		% cordero de dios...
		a1:m e1:m
		f1 c1
		d1:m a1:m f1 e1:7

		% cordero de dios...
		a1:m e1:m
		f1 c1
		% danos la paz...
		d1:m a1:m f1 a1:m
		d1:m a1:m f1 a1:m a1:m
	}
